project:
  type: website

website:
  title: "ryouready.github.io"
  site-url: https://friedliaaron.github.io/ryouready.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
